language: python
cache: pip
dist: xenial
jobs:
  include:
  - name: Python 3.7 Tests
    python: 3.7
    script: |
      poetry run black . --check
      poetry run mypy opsgenie_logger
      poetry run pytest
before_install: |
  pip install poetry
  poetry config settings.virtualenvs.in-project true
install: 'poetry install'
before_deploy:
  - poetry config http-basic.pypi __token__ $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish
  on:
    branch: master

env:
  global:
    secure: r7tJp2Vh/bnyKKlNMwgSsDVM3lYNGQW73cv40ZpklQ8GfU59suALcXbUIZM7twm8qv/Qi8LJe/6mSW7/I3st6W0Iej7HIW0/cx+Ky/Pb3LD4FDC/FXA2xKa+e9NwzdA3CD0PwYV5OkP2ng4mfzL+JsHya/T7uFAR2f3hLxk/6XoSXwxBKPM74pJNwwvi515ZQaJts2i5RkI5qTYKHbmSKVtzfbE0ZMP6doXf+ZxDZpc3EXCZGMyjECxfex+TuTcmO+HQgr1XZ7Zt8fB9fTXxtJLgPrazYkZBIVuNCmBqhy5YFNzFTUJEDuPLkZnljtE7zwyKRQQkAB02oO8x8HrHydxiIWyKliotK1yWbgi4DqHH5VkvvqLa1b+Kls+PkEnAy0E//Il9BOmA0TMXXTfUeMLAgFuuXh5x++9cVaNpSdUkJZWv0baIRdJMefjNc37Qtb43mB1IsDX9M1WrECpga2pf191SSPSuIUhQ9u7sBw1wZtNuG0sz0q8jmmNZqDgu6Db1hbkPVRNYvTq+NAFqaswOWTr5wv7UzE8Y25rD5TPCitDhJ0tPAAkSUDaOCzOX4oUgxwWPSyw0BVNLOcAlzDFcSZx7VWMlzW3ODma5b/zHfitAzuogwg2vCAjWLCwkTlcuwHi6r/YzDf6Abk/r2HsAdVOIbnZ7ona/HqwC7rU=
