language: python
cache: pip
dist: xenial
jobs:
  include:
  - name: Python 3.7 Tests
    python: 3.7
    script: |
      poetry run black . --check
      poetry run mypy opsgenie_logger
      poetry run pytest
before_install: |
  pip install poetry
  poetry config settings.virtualenvs.in-project true
install: poetry install
before_deploy:
- poetry config http-basic.pypi __token__ $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish --build
  on:
    branch: master
env:
  global:
    secure: qVif6Bao20qLaKMfocy+mUkJrZWT1b0E3qAVOzxwsZoBxiFTpEMW4OqeoaZMBZpadRtEeKMMcVMb7p5b2K5ScoilDsnJQGkYYRdp7wfioLU4nxis4dGcprxQySCIOpvZdxlkxP9RcIaCSL2RUvex/ijhbb4mLSEtNpzooqbFL6o/fvtJZha0q9dE7qoaN4LTA19ZfX0PNNBpd3P2p/tnAmrAVP9gnBX/35VqrHpu5OQsrz/U9TLcVsr8IJcLuT/YPYEAZ7YqYfjq3vkA3+dY/WB+Jmlp5HMbFKURJiAQNiwz4S3/A3cdu1TkHiyEzBPxK3rOQWOnZCuA6uN0e7KgbCp4AztSpCyG050dlF1WtrD2y6kJgcgtI2AnJsImNS220cJlb3D6YBnhM/70LfPXc7Z5D22RwH6npfqGsgxrkdBxFMsXY/UDMHFYdvpvGYwxhkttcAQ3HnscO3JSbkYxF4HdpR+xV7l81BodELfrodZkfqt/oPezTkOcE3qMWVL1B4L8Wq9BMNrPfzASGMXr5YeuhbmKoNnjKziPHuvbhQTDLwvLjV44oz0dHhRuplqFJNGWdno2v/KtYGqY9UYul4BhwcvFb98pu8xOGGSPD6EQUl1zWjGHpINUPehhv5fF8Gt1ma2KFBNshl0dfgEQasJ+X7TeRqWRC0VYdnVequY=
